server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:mysql://${ip}:${port}/${database}?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ${username}
    password: ${password}
    pool:
      validation-query: SELECT 1
      enabled: true
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10000
    database: 1
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG